matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9
      before_script:
        - chmod -R +x ./scripts
        - chmod +x ./tests/gradlew
      script:
        - cd app
        - xcodebuild -target ExperiBank -configuration Debug -destination 'platform=iOS,OS=9.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        - cd ..
        - ./scripts/zip-app.sh ExperiBank.app ExperiBank
        - ./scripts/upload-app.sh
        - cd tests
        - ./gradlew clean build -i --continue
