matrix:
  include:
    
    - language: objective-c
      os: osx
      osx_image: xcode9
      before_script:
        - chmod -R +x ./scripts
      script:
        - xcodebuild -target ExperiBank -configuration Debug -destination 'platform=iOS,OS=9.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        - ./scripts/zip-app.sh ExperiBank.app ExperiBank
        - ./scripts/upload-app.sh

    - language: java
          jdk: oraclejdk8
          before_script:
            - chmod +x ./gradlew
          script:
            - "./gradlew clean build -i --continue"
