matrix:
  include:
    - language: node_js
    os: osx
    - osx_image: xcode9
    node_js: "6"   
    script:
      - rm -rf build
      - npm install
      - ls -R .
      - chmod -R +x ./scripts
      - xcodebuild -target ExperiBank -configuration Debug -destination 'platform=iOS,OS=9.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - ./scripts/zip-app.sh ExperiBank.app ExperiBank
      - ./scripts/upload-app.sh

    - language: java
    before_install:
    - chmod +x gradlew
    script:
    - "./gradlew clean build -i --continue"