matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9
      before_script:
        - chmod -R +x 
      script:
        - xcodebuild -target ExperiBank -configuration Debug -destination 'platform=iOS,OS=9.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        - ./scripts/zip-app.sh ExperiBank.app ExperiBank
        - ./scripts/upload-app.sh

    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-25
          - build-tools-25.0.3
      before_script:
        - cd android/AppName
      script:
        - ./gradlew build connectedCheck

    

notifications:
  email:
    - yourname@gmail.com